# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ScroGlass
email: scroglass@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Scro Glass is a small lamp working collaborative featuring local talents from Rhode Island, Massachusetts, and Connecticut; the original creators of the Autopilot Torch Rig.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://scroglass.com" # the base hostname & protocol for your site
smedia_username: scroglass
github_username:  jwarner3412

# Build settings
markdown: kramdown
source: '_source/'
destination: '_site/'
collections:
  home_sections:
  gallery:
    path: 'images/gallery/'

sass:
  sass_dir: _sass
